// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqhrGD2r4dx9XyQDSVd0apYgs7r3wAvs',
    appId: '1:987116845823:web:bee56909335bd4fbfc6aca',
    messagingSenderId: '987116845823',
    projectId: 'med-ad',
    authDomain: 'med-ad.firebaseapp.com',
    storageBucket: 'med-ad.firebasestorage.app',
    measurementId: 'G-9L2X1SNVWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzE1srlqVALYIcFhV2jdIGiSq0oMgR6mE',
    appId: '1:987116845823:android:4f9514efd9381b3dfc6aca',
    messagingSenderId: '987116845823',
    projectId: 'med-ad',
    storageBucket: 'med-ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3nN4Nq-DnGI6xlhvB8I6Vsn5sp5MKj3o',
    appId: '1:987116845823:ios:8bdfe709f188a6ccfc6aca',
    messagingSenderId: '987116845823',
    projectId: 'med-ad',
    storageBucket: 'med-ad.firebasestorage.app',
    iosBundleId: 'com.squ.dawaiiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3nN4Nq-DnGI6xlhvB8I6Vsn5sp5MKj3o',
    appId: '1:987116845823:ios:5d71bc92db8b2bfffc6aca',
    messagingSenderId: '987116845823',
    projectId: 'med-ad',
    storageBucket: 'med-ad.firebasestorage.app',
    iosBundleId: 'com.example.medAdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpqhrGD2r4dx9XyQDSVd0apYgs7r3wAvs',
    appId: '1:987116845823:web:73b2f3393339d375fc6aca',
    messagingSenderId: '987116845823',
    projectId: 'med-ad',
    authDomain: 'med-ad.firebaseapp.com',
    storageBucket: 'med-ad.firebasestorage.app',
    measurementId: 'G-DYMMJ61DNT',
  );

}
